# PaperMeister developer convenience targets.
#
# The dependency lockfiles are the source of truth for reproducible installs:
#   requirements.lock      — runtime only        (from requirements.txt)
#   requirements-dev.lock  — runtime + dev/test  (from requirements-dev.txt)
#
# Both are universal (Linux/macOS/Windows via environment markers) and
# hash-pinned, compiled with a 3.12 floor (the app targets >=3.12). CI and
# release builds install with `pip install --require-hashes -r <lock>`.

# Keep the compile flags identical between `lock` and `lock-check`, or the drift
# check reports spurious diffs. Process substitution in lock-check needs bash.
SHELL    := bash
UV       ?= uv
PY_FLOOR ?= 3.12
COMPILE   = $(UV) pip compile --universal --python-version $(PY_FLOOR) --generate-hashes

.PHONY: lock lock-upgrade lock-check

# Regenerate both lockfiles. Run after editing requirements*.txt, then commit.
# uv treats an existing output file as pin preferences, so this only moves the
# versions it has to — an unrelated upstream release does not churn the lock.
lock:
	$(COMPILE) requirements.txt -o requirements.lock
	$(COMPILE) requirements-dev.txt -o requirements-dev.lock

# Deliberately bump every dependency to the newest version allowed by
# requirements*.txt. This is the only target that ignores the existing pins;
# run it when you actually want to take upstream updates, then commit.
lock-upgrade:
	$(COMPILE) --upgrade requirements.txt -o requirements.lock
	$(COMPILE) --upgrade requirements-dev.txt -o requirements-dev.lock

# Fail if the committed locks are stale relative to the requirements files
# (ignoring the autogenerated header/comment lines).
#
# The temp files are seeded with the committed locks so uv resolves with the
# same pin preferences `lock` uses. Compiling into an empty file instead would
# resolve everything fresh, so the check would fail every time any transitive
# dependency published a release — drift from upstream, not from our edits.
# Freshness is a separate concern, covered by pip-audit + `make lock-upgrade`.
lock-check:
	@set -e; \
	tmp_run=$$(mktemp); tmp_dev=$$(mktemp); \
	cp requirements.lock $$tmp_run; cp requirements-dev.lock $$tmp_dev; \
	$(COMPILE) requirements.txt -o $$tmp_run >/dev/null 2>&1; \
	$(COMPILE) requirements-dev.txt -o $$tmp_dev >/dev/null 2>&1; \
	if ! diff -q <(grep -v '^#' requirements.lock) <(grep -v '^#' $$tmp_run) >/dev/null; then \
		echo "requirements.lock is out of date. Run 'make lock' and commit."; \
		diff <(grep -v '^#' requirements.lock) <(grep -v '^#' $$tmp_run) || true; \
		rm -f $$tmp_run $$tmp_dev; exit 1; \
	fi; \
	if ! diff -q <(grep -v '^#' requirements-dev.lock) <(grep -v '^#' $$tmp_dev) >/dev/null; then \
		echo "requirements-dev.lock is out of date. Run 'make lock' and commit."; \
		diff <(grep -v '^#' requirements-dev.lock) <(grep -v '^#' $$tmp_dev) || true; \
		rm -f $$tmp_run $$tmp_dev; exit 1; \
	fi; \
	rm -f $$tmp_run $$tmp_dev; \
	echo "Lockfiles are up to date."
