# PaperMeister developer convenience targets.
#
# The dependency lockfiles are the source of truth for reproducible installs:
#   requirements.lock      — runtime only        (from requirements.txt)
#   requirements-dev.lock  — runtime + dev/test  (from requirements-dev.txt)
#
# Both are universal (Linux/macOS/Windows via environment markers) and
# hash-pinned, compiled with a 3.12 floor (the app targets >=3.12). CI and
# release builds install with `pip install --require-hashes -r <lock>`.

# Keep the compile flags identical between `lock` and `lock-check`, or the drift
# check reports spurious diffs. Process substitution in lock-check needs bash.
SHELL    := bash
UV       ?= uv
PY_FLOOR ?= 3.12
COMPILE   = $(UV) pip compile --universal --python-version $(PY_FLOOR) --generate-hashes

.PHONY: lock lock-check

# Regenerate both lockfiles. Run after editing requirements*.txt, then commit.
lock:
	$(COMPILE) requirements.txt -o requirements.lock
	$(COMPILE) requirements-dev.txt -o requirements-dev.lock

# Fail if the committed locks are stale relative to the requirements files
# (ignoring the autogenerated header/comment lines).
lock-check:
	@set -e; \
	tmp_run=$$(mktemp); tmp_dev=$$(mktemp); \
	$(COMPILE) requirements.txt -o $$tmp_run >/dev/null 2>&1; \
	$(COMPILE) requirements-dev.txt -o $$tmp_dev >/dev/null 2>&1; \
	if ! diff -q <(grep -v '^#' requirements.lock) <(grep -v '^#' $$tmp_run) >/dev/null; then \
		echo "requirements.lock is out of date. Run 'make lock' and commit."; \
		diff <(grep -v '^#' requirements.lock) <(grep -v '^#' $$tmp_run) || true; \
		rm -f $$tmp_run $$tmp_dev; exit 1; \
	fi; \
	if ! diff -q <(grep -v '^#' requirements-dev.lock) <(grep -v '^#' $$tmp_dev) >/dev/null; then \
		echo "requirements-dev.lock is out of date. Run 'make lock' and commit."; \
		diff <(grep -v '^#' requirements-dev.lock) <(grep -v '^#' $$tmp_dev) || true; \
		rm -f $$tmp_run $$tmp_dev; exit 1; \
	fi; \
	rm -f $$tmp_run $$tmp_dev; \
	echo "Lockfiles are up to date."
